project:
  type: website
  render:
    - "**/*.qmd"
    - "!**/resources/**/*.qmd"
  resources:
    - resources/images/
    - paseos/banners/

website:
  title: Jorge Cordero Zarate
  description: Blog de mis aventuras en bici.
  back-to-top-navigation: false
  page-footer:
    center: "© Coco"
    border: true
    background: light
  search:
    location: navbar
    type: overlay
    copy-button: true

  navbar:
    title: false
    background: "#212529"
    foreground: "#f8f9fa"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: bicycle
        href: paseos.qmd
        text: Paseos

    tools:
      - icon: instagram
        href: https://www.instagram.com/jcorde3/
        text: Instagram
        target: _blank
      - icon: facebook
        href: https://www.facebook.com/jcorde
        text: Facebook
        target: _blank

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    lightbox: true
    theme: [flatly, resources/styles/styles.scss]
    link-external-newwindow: true
    link-external-icon: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

execute:
  echo: false
  warning: false
